// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQTeEVG_WCewWqIBk5lnm5Eg_sP8Of6LE',
    appId: '1:628347069635:web:eab85aa5a29a04495a2e76',
    messagingSenderId: '628347069635',
    projectId: 'capipay',
    authDomain: 'capipay.firebaseapp.com',
    storageBucket: 'capipay.firebasestorage.app',
    measurementId: 'G-L0BRXEZ4TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj_rVU07pGtaHXShJKg1ABv68b-waTiLg',
    appId: '1:628347069635:android:cbf5bf433610e06c5a2e76',
    messagingSenderId: '628347069635',
    projectId: 'capipay',
    storageBucket: 'capipay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB26XDqcRpNkOuVgo7o5pSbIm252zpkH4w',
    appId: '1:628347069635:ios:f5ec796522fd8dd45a2e76',
    messagingSenderId: '628347069635',
    projectId: 'capipay',
    storageBucket: 'capipay.firebasestorage.app',
    iosBundleId: 'br.ufms.capipay.capipay',
  );
}
